### ISSUE TITLE
Can you clarify the source of the mortality data?

### ISSUE THREAD

**Issue by dreamerdad** [spiropan/CoVFR#2]
The study mentions "two independent, publicly available data sources from the US and Europe." Can you add clarification on the specific source of these data sets in README.md?

**Comment by spiropan** [comment]
Thanks for your note. I added clarification in the README.md file that the full links to the original datasets can be found in the Data Sources section of the manuscript and included a link in the README.md file. Don't know how I managed to omit before..thanks again!

**Comment by dreamerdad** [comment]
Thank you for replying. The Readme file now says "For links to the original data sources, please see the Data Sources section in our manuscript (see link above)."

Can you clarify where one can find that section and the mortality data as I am still having trouble finding the links to the underlying mortality data sources for Y20, Y21 age-stratified death counts. I see reference to https://data.cdc.gov/NCHS/Provisional-COVID-19-Deaths-by-Sex-and-Age/9bhg-hcku but this relates to COVID-19 - associated deaths.  I also see reference to https://www.statista.com/statistics/241572/death-rate-by-age-and-sex-in-the-us/  but this is mortality data for 2018 and it is from statista.com and the underlying data source is not publicly visible.

**Comment by spiropan** [comment]
The first link you mention is the right data source. It includes a column with total deaths as well (not just COVID associated deaths).

**Comment by dreamerdad** [comment]
Thank you, Dr Pantazatos!
